ngo/config/routes.rb
Rails.application.routes.draw do
  resources :country_data_finals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

ngo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ngo/app/models/country_data_final.rb
class CountryDataFinal < ApplicationRecord
end

ngo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

ngo/app/controllers/country_data_finals_controller.rb
class CountryDataFinalsController < ApplicationController
  before_action :set_country_data_final, only: %i[ show edit update destroy ]

  # GET /country_data_finals or /country_data_finals.json
  def index
    @country_data_finals = CountryDataFinal.all
  end

  # GET /country_data_finals/1 or /country_data_finals/1.json
  def show
  end

  # GET /country_data_finals/new
  def new
    @country_data_final = CountryDataFinal.new
  end

  # GET /country_data_finals/1/edit
  def edit
  end

  # POST /country_data_finals or /country_data_finals.json
  def create
    @country_data_final = CountryDataFinal.new(country_data_final_params)

    respond_to do |format|
      if @country_data_final.save
        format.html { redirect_to @country_data_final, notice: "Country data final was successfully created." }
        format.json { render :show, status: :created, location: @country_data_final }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country_data_final.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /country_data_finals/1 or /country_data_finals/1.json
  def update
    respond_to do |format|
      if @country_data_final.update(country_data_final_params)
        format.html { redirect_to @country_data_final, notice: "Country data final was successfully updated." }
        format.json { render :show, status: :ok, location: @country_data_final }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country_data_final.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /country_data_finals/1 or /country_data_finals/1.json
  def destroy
    @country_data_final.destroy!

    respond_to do |format|
      format.html { redirect_to country_data_finals_path, status: :see_other, notice: "Country data final was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country_data_final
      @country_data_final = CountryDataFinal.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def country_data_final_params
      params.expect(country_data_final: [ :name, :mobilephones, :mortalityunder5, :healthexpenditurepercapita, :healthexpenditureppercentgdp, :population, :populationurban, :birthrate, :lifeexpectancy, :gdp ])
    end
end

ngo/app/helpers/application_helper.rb
module ApplicationHelper
end

ngo/app/helpers/country_data_finals_helper.rb
module CountryDataFinalsHelper
end

ngo/app/views/country_data_finals/_country_data_final.html.erb
  <div id="<%= dom_id country_data_final %>" class="w3-card w3-margin w3-padding w3-light-grey w3-round">
  <div class="w3-container">
    <p>
      <strong>Name:</strong>
      <span class="w3-text-teal"><%= country_data_final.name %></span>
    </p>

    <p>
      <strong>Mobile Phones:</strong>
      <span class="w3-text-teal"><%= country_data_final.mobilephones %></span>
    </p>

    <p>
      <strong>Mortality under 5:</strong>
      <span class="w3-text-teal"><%= country_data_final.mortalityunder5 %></span>
    </p>

    <p>
      <strong>Health Expenditure Per Capita:</strong>
      <span class="w3-text-teal"><%= country_data_final.healthexpenditurepercapita %></span>
    </p>

    <p>
      <strong>Health Expenditure (% GDP):</strong>
      <span class="w3-text-teal"><%= country_data_final.healthexpenditureppercentgdp %></span>
    </p>

    <p>
      <strong>Population:</strong>
      <span class="w3-text-teal"><%= country_data_final.population %></span>
    </p>

    <p>
      <strong>Urban Population:</strong>
      <span class="w3-text-teal"><%= country_data_final.populationurban %></span>
    </p>

    <p>
      <strong>Birth Rate:</strong>
      <span class="w3-text-teal"><%= country_data_final.birthrate %></span>
    </p>

    <p>
      <strong>Life Expectancy:</strong>
      <span class="w3-text-teal"><%= country_data_final.lifeexpectancy %></span>
    </p>

    <p>
      <strong>GDP:</strong>
      <span class="w3-text-teal"><%= country_data_final.gdp %></span>
    </p>
  </div>
</div>

ngo/app/views/country_data_finals/_form.html.erb
<%= form_with(model: country_data_final) do |form| %>
  <% if country_data_final.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country_data_final.errors.count, "error") %> prohibited this country_data_final from being saved:</h2>

      <ul>
        <% country_data_final.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.textarea :name %>
  </div>

  <div>
    <%= form.label :mobilephones, style: "display: block" %>
    <%= form.text_field :mobilephones %>
  </div>

  <div>
    <%= form.label :mortalityunder5, style: "display: block" %>
    <%= form.text_field :mortalityunder5 %>
  </div>

  <div>
    <%= form.label :healthexpenditurepercapita, style: "display: block" %>
    <%= form.text_field :healthexpenditurepercapita %>
  </div>

  <div>
    <%= form.label :healthexpenditureppercentgdp, style: "display: block" %>
    <%= form.text_field :healthexpenditureppercentgdp %>
  </div>

  <div>
    <%= form.label :population, style: "display: block" %>
    <%= form.text_field :population %>
  </div>

  <div>
    <%= form.label :populationurban, style: "display: block" %>
    <%= form.text_field :populationurban %>
  </div>

  <div>
    <%= form.label :birthrate, style: "display: block" %>
    <%= form.text_field :birthrate %>
  </div>

  <div>
    <%= form.label :lifeexpectancy, style: "display: block" %>
    <%= form.text_field :lifeexpectancy %>
  </div>

  <div>
    <%= form.label :gdp, style: "display: block" %>
    <%= form.text_field :gdp %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ngo/app/views/country_data_finals/edit.html.erb
<% content_for :title, "Editing country data final" %>

<h1>Editing country data final</h1>

<%= render "form", country_data_final: @country_data_final %>

<br>

<div>
  <%= link_to "Show this country data final", @country_data_final %> |
  <%= link_to "Back to country data finals", country_data_finals_path %>
</div>

ngo/app/views/country_data_finals/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="w3-panel w3-pale-green w3-border w3-border-green w3-round">
  <%= notice %>
</div>

<% content_for :title, "Country Data Finals" %>

<h1 class="w3-center w3-text-teal">Country Data Finals</h1>

<div id="country_data_finals" class="w3-container">
  <% @country_data_finals.each do |country_data_final| %>
    <div class="w3-card w3-margin w3-padding">
      <%= render country_data_final %>
      <p>
        <%= link_to "Show this Country Data Final", country_data_final, class: "w3-button w3-teal w3-round" %>
      </p>
    </div>
  <% end %>
</div>

<p>
  <%= link_to "New Country Data Final", new_country_data_final_path, class: "w3-button w3-green w3-round" %>
</p>

ngo/app/views/country_data_finals/new.html.erb
<% content_for :title, "New country data final" %>

<h1>New country data final</h1>

<%= render "form", country_data_final: @country_data_final %>

<br>

<div>
  <%= link_to "Back to country data finals", country_data_finals_path %>
</div>

ngo/app/views/country_data_finals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country_data_final %>

<div>
  <%= link_to "Edit this country data final", edit_country_data_final_path(@country_data_final) %> |
  <%= link_to "Back to country data finals", country_data_finals_path %>

  <%= button_to "Destroy this country data final", @country_data_final, method: :delete %>
</div>

ngo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ngo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>